name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

# GitHub OIDC permissions
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./parent_module

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./parent_module

      # 6. Terraform Plan
      # Runs on:
      # - feature branch push
      # - pull request to main
      # - main branch push
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./parent_module

      # 7. Terraform Apply
      # Apply ONLY when code is pushed directly to main
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
        working-directory: ./parent_module